title: gmd20
description:  personal blog

url: http://gmd20.github.io
baseurl: ""
paginate_path: "blog/page:num/"
paginate: 5
permalink: blog/:title/ 
markdown: redcarpet
highlighter: pygments

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      author: "gmd20"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "gmd20"
  -
    scope:
      path: "linux"
      type: "posts"
    values:
      layout: "post"
      category: "linux"
      author: "gmd20"
    
      
