title: gmd20
description:  personal blog

url: http://gmd20.github.io
baseurl: ""
paginate_path: "blog/page:num/"
paginate: 5
permalink: blog/:title/
markdown: redcarpet
highlighter: pygments

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact
